// // const PDFDocument = require('pdfkit');

// const generateInvoicePDF = (invoice, type = 'Invoice') => {
//   const doc = new PDFDocument({ margin: 50, size: 'A4' });

//   // Header
//   doc.rect(0, 0, doc.page.width, 80).fill('#1E40AF');
//   doc.fillColor('white').fontSize(26).font('Helvetica-Bold')
//     .text('MANGALYOG ENTERPRISE', 50, 25);
//   doc.fontSize(11).font('Helvetica')
//     .text(`Billing & Site Management`, 50, 55);

//   doc.fillColor('black');

//   // Document type + number
//   const docNum = type === 'Invoice' ? invoice.invoiceNumber : invoice.quotationNumber;
//   doc.moveDown(2);
//   doc.fontSize(20).font('Helvetica-Bold').text(type.toUpperCase(), { align: 'right' });
//   doc.fontSize(11).font('Helvetica').text(`#${docNum}`, { align: 'right' });
//   doc.moveDown();

//   // Site info box
//   const site = invoice.siteId;
//   doc.fontSize(11).font('Helvetica-Bold').text('Billed To:');
//   doc.font('Helvetica').fontSize(10)
//     .text(site?.name || 'N/A')
//     .text(site?.address || '')
//     .text(site?.ownerName ? `Owner: ${site.ownerName}` : '')
//     .text(site?.phone ? `Phone: ${site.phone}` : '')
//     .text(site?.gstNumber ? `GST: ${site.gstNumber}` : '');

//   doc.moveDown();

//   // Meta
//   doc.fontSize(10).font('Helvetica')
//     .text(`Date: ${new Date(invoice.date).toLocaleDateString('en-IN')}`, { align: 'right' })
//     .text(`Due Date: ${invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString('en-IN') : 'N/A'}`, { align: 'right' })
//     .text(`Status: ${invoice.status?.toUpperCase()}`, { align: 'right' });

//   doc.moveDown();

//   // Items table header
//   const tableTop = doc.y;
//   const col = { desc: 50, qty: 290, rate: 360, amount: 460 };

//   doc.rect(50, tableTop, doc.page.width - 100, 22).fill('#1E40AF');
//   doc.fillColor('white').fontSize(10).font('Helvetica-Bold')
//     .text('Description', col.desc + 4, tableTop + 5)
//     .text('Qty', col.qty, tableTop + 5)
//     .text('Rate', col.rate, tableTop + 5)
//     .text('Amount', col.amount, tableTop + 5);

//   doc.fillColor('black');
//   let rowY = tableTop + 28;

//   (invoice.items || []).forEach((item, i) => {
//     const bg = i % 2 === 0 ? '#F1F5F9' : '#FFFFFF';
//     doc.rect(50, rowY - 4, doc.page.width - 100, 20).fill(bg);
//     doc.fillColor('black').font('Helvetica').fontSize(10)
//       .text(item.description, col.desc + 4, rowY, { width: 230 })
//       .text(String(item.quantity), col.qty, rowY)
//       .text(`Rs.${item.rate.toLocaleString('en-IN')}`, col.rate, rowY)
//       .text(`Rs.${item.amount.toLocaleString('en-IN')}`, col.amount, rowY);
//     rowY += 24;
//   });

//   doc.moveDown(2);

//   // Totals
//   doc.font('Helvetica').fontSize(10)
//     .text(`Subtotal: Rs.${invoice.subtotal?.toLocaleString('en-IN') || 0}`, { align: 'right' })
//     .text(`Tax (${invoice.taxRate || 0}%): Rs.${invoice.taxAmount?.toLocaleString('en-IN') || 0}`, { align: 'right' });

//   doc.font('Helvetica-Bold').fontSize(13)
//     .text(`Total: Rs.${invoice.total?.toLocaleString('en-IN')}`, { align: 'right' });

//   if (invoice.notes) {
//     doc.moveDown();
//     doc.font('Helvetica-Bold').fontSize(10).text('Notes:');
//     doc.font('Helvetica').fontSize(10).text(invoice.notes);
//   }

//   // Footer
//   doc.fontSize(9).fillColor('grey')
//     .text('Generated by Mangalyog Enterprise', 50, doc.page.height - 50, { align: 'center' });

//   return doc;
// };

// module.exports = { generateInvoicePDF };

const PDFDocument = require('pdfkit');
const path = require('path');

const generateInvoicePDF = (invoice, type = 'Invoice') => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });

  /* ================= WATERMARK LOGO ================= */
  const logoPath = path.join(__dirname, '../assets/logo.png');

  const logoWidth = 500;
  const centerX = (doc.page.width - logoWidth) / 2;
  const centerY = (doc.page.height - logoWidth) / 2;

  doc.save();
  doc.opacity(0.06);
  doc.image(logoPath, centerX, centerY, { width: logoWidth });
  doc.restore();

  /* ================= TOP ORANGE BAR ================= */
  doc.rect(0, 0, doc.page.width, 10).fill('#F97316');

  /* ================= COMPANY DETAILS ================= */
  doc.fillColor('black')
    .fontSize(14)
    .font('Helvetica-Bold')
    .text('Mangalyog Enterprise', 50, 30);

  doc.fontSize(10)
    .font('Helvetica')
    .text('Near Virbhadreshwar mandir, Ringroad', 50, 50)
    .text('Latur - 413512', 50, 65)
    .text(`Mob: ${invoice.companyPhone || '9707874042'}`, 50, 80)
    .text(`Email: mangalyogentp@gmail.com`, 50, 95)
    .text(`GSTIN: ${invoice.gst || '27CVTPP0520Q1ZU'}`, 50, 110);

  /* ================= DATE & DOC NO ================= */
  const docNum = type === 'Invoice'
    ? invoice.invoiceNumber
    : invoice.quotationNumber;

  doc.fontSize(10)
    .text(`DATE: ${new Date(invoice.date).toLocaleDateString('en-IN')}`, 400, 30)
    .text(`${type.toUpperCase()} NO: ${docNum}`, 400, 50);

  /* ================= TO ================= */
  const site = invoice.siteId;

  doc.moveDown(4);

  doc.font('Helvetica-Bold').text('TO:', 50, 150);
  doc.font('Helvetica')
    .text(site?.name || 'N/A', 50, 165)
    .text(site?.address || '', 50, 180);

  /* ================= FROM ================= */
  doc.font('Helvetica-Bold').text('From', 300, 150);
  doc.font('Helvetica')
    .text(`Name: ${invoice.senderName || 'Raghuraj Patil'}`, 300, 165)
    .text(`Company: Mangalyog Enterprise`, 300, 180)
    .text(`Address: Ringroad, Latur`, 300, 195)
    .text(`Phone: ${invoice.companyPhone || '9707874042'}`, 300, 210);

  /* ================= TABLE ================= */
  let tableTop = 250;

  const col = {
    sr: 50,
    desc: 80,
    qty: 320,
    rate: 380,
    amount: 460
  };

  doc.rect(50, tableTop, doc.page.width - 100, 25).stroke();

  doc.font('Helvetica-Bold').fontSize(10)
    .text('#', col.sr + 5, tableTop + 8)
    .text('ITEM DESCRIPTION', col.desc, tableTop + 8)
    .text('QTY', col.qty, tableTop + 8)
    .text('Rate/Qty', col.rate, tableTop + 8)
    .text('Total Amount', col.amount, tableTop + 8);

  let rowY = tableTop + 30;

  (invoice.items || []).forEach((item, i) => {
    const amount = item.amount || (item.quantity * item.rate);

    doc.rect(50, rowY - 5, doc.page.width - 100, 40).stroke();

    doc.font('Helvetica').fontSize(10)
      .text(i + 1, col.sr + 5, rowY)
      .text(item.description, col.desc, rowY, { width: 220 })
      .text(item.quantity, col.qty, rowY) // ✅ FIXED HERE
      .text(`Rs.${item.rate.toLocaleString('en-IN')}`, col.rate, rowY)
      .text(`Rs.${amount.toLocaleString('en-IN')}`, col.amount, rowY);

    rowY += 45;
  });

  /* ================= TOTAL SECTION ================= */
  const subtotal = invoice.subtotal || 0;
  const tax = invoice.taxAmount || 0;
  const total = invoice.total || 0;

  doc.rect(300, rowY, 250, 80).stroke();

  doc.font('Helvetica')
    .text('Subtotal', 310, rowY + 10)
    .text(`Rs.${subtotal.toLocaleString('en-IN')}`, 450, rowY + 10)

    .text(`GST ${invoice.taxRate || 0}%`, 310, rowY + 30)
    .text(`Rs.${tax.toLocaleString('en-IN')}`, 450, rowY + 30);

  doc.font('Helvetica-Bold')
    .text('Grand Total', 310, rowY + 55)
    .text(`Rs.${total.toLocaleString('en-IN')}`, 450, rowY + 55);

  /* ================= NOTES ================= */
  doc.font('Helvetica-Bold')
    .text('Note:', 50, rowY + 100);

  doc.font("Helvetica").fontSize(9);

  let notesArray = [];

  // ✅ supports both array & string
  if (Array.isArray(invoice.notes)) {
    notesArray = invoice.notes;
  } else if (typeof invoice.notes === "string") {
    notesArray = invoice.notes.split("\n");
  }

  let y = rowY + 115;

  notesArray.forEach((note, index) => {
    if (note.trim() !== "") {
      doc.text(`${index + 1}. ${note}`, 50, y, { width: 500 });
      y += doc.heightOfString(note, { width: 500 }) + 5;
    }
  });

  /* ================= BOTTOM ORANGE BAR ================= */
  doc.rect(0, doc.page.height - 20, doc.page.width, 10).fill('#F97316');

  return doc;
};

module.exports = { generateInvoicePDF };