// // const PDFDocument = require('pdfkit');

// const generateInvoicePDF = (invoice, type = 'Invoice') => {
//   const doc = new PDFDocument({ margin: 50, size: 'A4' });

//   // Header
//   doc.rect(0, 0, doc.page.width, 80).fill('#1E40AF');
//   doc.fillColor('white').fontSize(26).font('Helvetica-Bold')
//     .text('MANGALYOG ENTERPRISE', 50, 25);
//   doc.fontSize(11).font('Helvetica')
//     .text(`Billing & Site Management`, 50, 55);

//   doc.fillColor('black');

//   // Document type + number
//   const docNum = type === 'Invoice' ? invoice.invoiceNumber : invoice.quotationNumber;
//   doc.moveDown(2);
//   doc.fontSize(20).font('Helvetica-Bold').text(type.toUpperCase(), { align: 'right' });
//   doc.fontSize(11).font('Helvetica').text(`#${docNum}`, { align: 'right' });
//   doc.moveDown();

//   // Site info box
//   const site = invoice.siteId;
//   doc.fontSize(11).font('Helvetica-Bold').text('Billed To:');
//   doc.font('Helvetica').fontSize(10)
//     .text(site?.name || 'N/A')
//     .text(site?.address || '')
//     .text(site?.ownerName ? `Owner: ${site.ownerName}` : '')
//     .text(site?.phone ? `Phone: ${site.phone}` : '')
//     .text(site?.gstNumber ? `GST: ${site.gstNumber}` : '');

//   doc.moveDown();

//   // Meta
//   doc.fontSize(10).font('Helvetica')
//     .text(`Date: ${new Date(invoice.date).toLocaleDateString('en-IN')}`, { align: 'right' })
//     .text(`Due Date: ${invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString('en-IN') : 'N/A'}`, { align: 'right' })
//     .text(`Status: ${invoice.status?.toUpperCase()}`, { align: 'right' });

//   doc.moveDown();

//   // Items table header
//   const tableTop = doc.y;
//   const col = { desc: 50, qty: 290, rate: 360, amount: 460 };

//   doc.rect(50, tableTop, doc.page.width - 100, 22).fill('#1E40AF');
//   doc.fillColor('white').fontSize(10).font('Helvetica-Bold')
//     .text('Description', col.desc + 4, tableTop + 5)
//     .text('Qty', col.qty, tableTop + 5)
//     .text('Rate', col.rate, tableTop + 5)
//     .text('Amount', col.amount, tableTop + 5);

//   doc.fillColor('black');
//   let rowY = tableTop + 28;

//   (invoice.items || []).forEach((item, i) => {
//     const bg = i % 2 === 0 ? '#F1F5F9' : '#FFFFFF';
//     doc.rect(50, rowY - 4, doc.page.width - 100, 20).fill(bg);
//     doc.fillColor('black').font('Helvetica').fontSize(10)
//       .text(item.description, col.desc + 4, rowY, { width: 230 })
//       .text(String(item.quantity), col.qty, rowY)
//       .text(`Rs.${item.rate.toLocaleString('en-IN')}`, col.rate, rowY)
//       .text(`Rs.${item.amount.toLocaleString('en-IN')}`, col.amount, rowY);
//     rowY += 24;
//   });

//   doc.moveDown(2);

//   // Totals
//   doc.font('Helvetica').fontSize(10)
//     .text(`Subtotal: Rs.${invoice.subtotal?.toLocaleString('en-IN') || 0}`, { align: 'right' })
//     .text(`Tax (${invoice.taxRate || 0}%): Rs.${invoice.taxAmount?.toLocaleString('en-IN') || 0}`, { align: 'right' });

//   doc.font('Helvetica-Bold').fontSize(13)
//     .text(`Total: Rs.${invoice.total?.toLocaleString('en-IN')}`, { align: 'right' });

//   if (invoice.notes) {
//     doc.moveDown();
//     doc.font('Helvetica-Bold').fontSize(10).text('Notes:');
//     doc.font('Helvetica').fontSize(10).text(invoice.notes);
//   }

//   // Footer
//   doc.fontSize(9).fillColor('grey')
//     .text('Generated by Mangalyog Enterprise', 50, doc.page.height - 50, { align: 'center' });

//   return doc;
// };

// module.exports = { generateInvoicePDF };

const PDFDocument = require('pdfkit');
const path = require('path');

function numberToWords(num) {
  const a = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten",
    "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen",
    "Eighteen", "Nineteen"];
  const b = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"];

  if (num === 0) return "Zero";
  if (num < 20) return a[num];
  if (num < 100) return b[Math.floor(num / 10)] + " " + a[num % 10];
  if (num < 1000) return a[Math.floor(num / 100)] + " Hundred " + numberToWords(num % 100);
  if (num < 100000) return numberToWords(Math.floor(num / 1000)) + " Thousand " + numberToWords(num % 1000);
  if (num < 10000000) return numberToWords(Math.floor(num / 100000)) + " Lakh " + numberToWords(num % 100000);
  return num;
}

const generateInvoicePDF = (invoice, type = 'Invoice') => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });

  /* ========= WATERMARK ========= */
  const logoPath = path.join(__dirname, '../assets/logo.png');
  doc.save();
  doc.opacity(0.06);
  doc.image(logoPath, 100, 220, { width: 400 });
  doc.restore();

  /* ========= TOP ORANGE LINE ========= */
  doc.rect(0, 35, doc.page.width, 10).fill('#EA580C');

  /* ========= COMPANY ========= */
  doc.fillColor('black')
    .font('Helvetica-Bold')
    .fontSize(14)
    .text('Mangalyog Enterprise', 50, 55);

  doc.font('Helvetica').fontSize(10)
    .text('Near Virbhadreshwar mandir, Ringroad', 50, 75)
    .text('Latur - 413512', 50, 90)
    .text(`Mob. No - ${invoice.companyPhone || '9970874042'}`, 50, 105)
    .text('E-Mail ID - mangalyogentp@gmail.com', 50, 120)
    .text(`GSTIN-${invoice.gst || '27CVTPP0520Q1ZU'}`, 50, 135);

  /* ========= RIGHT SIDE ========= */
  const docNum = type === 'Invoice'
    ? invoice.invoiceNumber
    : invoice.quotationNumber;

  doc.font('Helvetica').fontSize(10)
    .text(`DATE - ${new Date(invoice.date).toLocaleDateString('en-IN')}`, 400, 55);

  doc.moveTo(400, 80).lineTo(550, 80).stroke();

  doc.font('Helvetica-Bold')
    .text(`${type === 'Invoice' ? 'INVOICE NO.' : 'QUOTE NO.'} ${docNum}`, 400, 100);

  doc.moveTo(400, 120).lineTo(550, 120).stroke();

  /* ========= TO ========= */
  const site = invoice.siteId;

  doc.font('Helvetica-Bold').text('TO:', 50, 180);
  doc.font('Helvetica')
    .text(site?.name || '', 50, 195)
    .text(site?.address || '', 50, 210);

  doc.moveTo(50, 230).lineTo(250, 230).stroke();

  /* ========= FROM ========= */
  doc.font('Helvetica-Bold').text('From', 350, 180);

  doc.font('Helvetica')
    .text(`Name - ${invoice.senderName || 'Raghuraj Patil'}`, 350, 195)
    .text('Company Name - Mangalyog Enterprise', 350, 210)
    .text('Address - Ringroad, Latur', 350, 225)
    .text(`Phone - ${invoice.companyPhone || '9707874042'}`, 350, 240);

  /* ================= TABLE ================= */
let tableTop = 260;
const tableWidth = doc.page.width - 100;
const left = 50;
const right = doc.page.width - 50;

// PERFECT COLUMN ALIGNMENT (FIXED)
const col = {
  sr: left,
  srEnd: left + 40,

  desc: left + 40,
  descEnd: left + 260,

  qty: left + 260,
  qtyEnd: left + 320,

  rate: left + 320,
  rateEnd: left + 400,

  amount: left + 400,
  amountEnd: right
};

// HEADER BOX
doc.rect(left, tableTop, tableWidth, 25).stroke();

// HEADER TEXT
doc.font('Helvetica-Bold')
  .text('#', col.sr + 10, tableTop + 8)
  .text('ITEM DESCRIPTION', col.desc + 5, tableTop + 8)
  .text('QTY', col.qty + 5, tableTop + 8)
  .text('Rate/Qty', col.rate + 5, tableTop + 8)
  .text('Total Amount', col.amount + 5, tableTop + 8);

let rowY = tableTop + 25;

/* ================= ITEMS ================= */
(invoice.items || []).forEach((item, i) => {
  const amount = item.amount || item.quantity * item.rate;

  doc.rect(left, rowY, tableWidth, 40).stroke();

  doc.font('Helvetica')
    .text(i + 1, col.sr + 10, rowY + 10)
    .text(item.description, col.desc + 5, rowY + 5, { width: 200 })
    .text(item.quantity, col.qty + 5, rowY + 10)
    .text(`Rs.${item.rate.toLocaleString('en-IN')}`, col.rate + 5, rowY + 10)
    .text(`Rs.${amount.toLocaleString('en-IN')}`, col.amount + 5, rowY + 10);

  rowY += 40;
});

/* ================= EMPTY ROW ================= */
doc.rect(left, rowY, tableWidth, 40).stroke();
rowY += 40;

/* ================= TOTAL ================= */
const totalStartX = col.rate;

doc.rect(left, rowY, tableWidth, 30).stroke();
doc.text('Subtotal', totalStartX + 5, rowY + 8)
   .text(`Rs.${(invoice.subtotal || 0).toLocaleString('en-IN')}`, col.amount + 5, rowY + 8);
rowY += 30;

doc.rect(left, rowY, tableWidth, 30).stroke();
doc.text(`GST ${invoice.taxRate || 0}%`, totalStartX + 5, rowY + 8)
   .text(`Rs.${(invoice.taxAmount || 0).toLocaleString('en-IN')}`, col.amount + 5, rowY + 8);
rowY += 30;

doc.rect(left, rowY, tableWidth, 30).stroke();
doc.font('Helvetica-Bold')
  .text('Grand Total', totalStartX + 5, rowY + 8)
  .text(`Rs.${(invoice.total || 0).toLocaleString('en-IN')}`, col.amount + 5, rowY + 8);
doc.font('Helvetica');

rowY += 30;

/* ================= IN WORD ================= */
doc.rect(left, rowY, tableWidth, 30).stroke();

doc.font('Helvetica-Bold')
  .text('In Word:', left + 10, rowY + 8);

doc.font('Helvetica')
  .text(
    numberToWords(Math.floor(invoice.total || 0)) + ' only',
    left + 100,
    rowY + 8
  );

/* ================= PERFECT VERTICAL LINES ================= */

// FINAL HEIGHT (VERY IMPORTANT FIX)
const finalBottom = rowY + 30;

// DRAW LINES FULL HEIGHT (NO BREAKS)
[
  col.srEnd,
  col.descEnd,
  col.qtyEnd,
  col.rateEnd,
  col.amountEnd
].forEach(x => {
  doc.moveTo(x, tableTop)
     .lineTo(x, finalBottom)
     .stroke();
});
  /* ========= NOTES ========= */
  doc.font('Helvetica-Bold')
    .text('Note :', 50, rowY + 50);

  doc.font('Helvetica');

  let notes = Array.isArray(invoice.notes)
    ? invoice.notes
    : (invoice.notes || '').split('\n');

  let y = rowY + 65;

  notes.forEach((note, i) => {
    if (note.trim()) {
      doc.text(`${i + 1}. ${note}`, 50, y);
      y += 15;
    }
  });

  /* ========= BOTTOM ORANGE ========= */
  doc.rect(0, doc.page.height - 40, doc.page.width, 10).fill('#EA580C');

  return doc;
};

module.exports = { generateInvoicePDF };