const PDFDocument = require('pdfkit');

const generateInvoicePDF = (invoice, type = 'Invoice') => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  // Header
  doc.rect(0, 0, doc.page.width, 80).fill('#1E40AF');
  doc.fillColor('white').fontSize(26).font('Helvetica-Bold')
    .text('MANGALYOG ENTERPRISE', 50, 25);
  doc.fontSize(11).font('Helvetica')
    .text(`Billing & Site Management`, 50, 55);

  doc.fillColor('black');

  // Document type + number
  const docNum = type === 'Invoice' ? invoice.invoiceNumber : invoice.quotationNumber;
  doc.moveDown(2);
  doc.fontSize(20).font('Helvetica-Bold').text(type.toUpperCase(), { align: 'right' });
  doc.fontSize(11).font('Helvetica').text(`#${docNum}`, { align: 'right' });
  doc.moveDown();

  // Site info box
  const site = invoice.siteId;
  doc.fontSize(11).font('Helvetica-Bold').text('Billed To:');
  doc.font('Helvetica').fontSize(10)
    .text(site?.name || 'N/A')
    .text(site?.address || '')
    .text(site?.ownerName ? `Owner: ${site.ownerName}` : '')
    .text(site?.phone ? `Phone: ${site.phone}` : '')
    .text(site?.gstNumber ? `GST: ${site.gstNumber}` : '');

  doc.moveDown();

  // Meta
  doc.fontSize(10).font('Helvetica')
    .text(`Date: ${new Date(invoice.date).toLocaleDateString('en-IN')}`, { align: 'right' })
    .text(`Due Date: ${invoice.dueDate ? new Date(invoice.dueDate).toLocaleDateString('en-IN') : 'N/A'}`, { align: 'right' })
    .text(`Status: ${invoice.status?.toUpperCase()}`, { align: 'right' });

  doc.moveDown();

  // Items table header
  const tableTop = doc.y;
  const col = { desc: 50, qty: 290, rate: 360, amount: 460 };

  doc.rect(50, tableTop, doc.page.width - 100, 22).fill('#1E40AF');
  doc.fillColor('white').fontSize(10).font('Helvetica-Bold')
    .text('Description', col.desc + 4, tableTop + 5)
    .text('Qty', col.qty, tableTop + 5)
    .text('Rate', col.rate, tableTop + 5)
    .text('Amount', col.amount, tableTop + 5);

  doc.fillColor('black');
  let rowY = tableTop + 28;

  (invoice.items || []).forEach((item, i) => {
    const bg = i % 2 === 0 ? '#F1F5F9' : '#FFFFFF';
    doc.rect(50, rowY - 4, doc.page.width - 100, 20).fill(bg);
    doc.fillColor('black').font('Helvetica').fontSize(10)
      .text(item.description, col.desc + 4, rowY, { width: 230 })
      .text(String(item.quantity), col.qty, rowY)
      .text(`Rs.${item.rate.toLocaleString('en-IN')}`, col.rate, rowY)
      .text(`Rs.${item.amount.toLocaleString('en-IN')}`, col.amount, rowY);
    rowY += 24;
  });

  doc.moveDown(2);

  // Totals
  doc.font('Helvetica').fontSize(10)
    .text(`Subtotal: Rs.${invoice.subtotal?.toLocaleString('en-IN') || 0}`, { align: 'right' })
    .text(`Tax (${invoice.taxRate || 0}%): Rs.${invoice.taxAmount?.toLocaleString('en-IN') || 0}`, { align: 'right' });

  doc.font('Helvetica-Bold').fontSize(13)
    .text(`Total: Rs.${invoice.total?.toLocaleString('en-IN')}`, { align: 'right' });

  if (invoice.notes) {
    doc.moveDown();
    doc.font('Helvetica-Bold').fontSize(10).text('Notes:');
    doc.font('Helvetica').fontSize(10).text(invoice.notes);
  }

  // Footer
  doc.fontSize(9).fillColor('grey')
    .text('Generated by Mangalyog Enterprise', 50, doc.page.height - 50, { align: 'center' });

  return doc;
};

module.exports = { generateInvoicePDF };
